-- currently localized for enUS/enGB.  mwayne@gmail.com for translations, thanks!

--if (GetLocale() == "enUS" or GetLocale() == "enGB") then

DFILTER_BACKDROP_TOOLTIP = "Shift+left click to move.\nCtrl+right click to change time orientation."

DFILTER_OPTIONS_TARGET = "Target:"
DFILTER_OPTIONS_GROW = "Grow:"
DFILTER_OPTIONS_ROW = "Buffs per row"
DFILTER_OPTIONS_SELFAPPLIED = "Self-applied only"
DFILTER_OPTIONS_DONTCOMBINE = "Don't Combine Stacks"
DFILTER_OPTIONS_NAME = "Buff/Debuff name:"
DFILTER_OPTIONS_TEXTURE = "Texture (optional):"
DFILTER_OPTIONS_ADD = "Add"
DFILTER_OPTIONS_DEL = "Del"
DFILTER_OPTIONS_DEBUFFS = "Debuffs"
DFILTER_OPTIONS_BUFFS = "Buffs"
DFILTER_OPTIONS_SETTINGS = "Settings"
DFILTER_OPTIONS_DEBUFF_FILTERING = "Debuff Filtering"
DFILTER_OPTIONS_BUFF_FILTERING = "Buff Filtering"
DFILTER_OPTIONS_PDEBUFF_FILTERING = "Player Debuff Filtering"
DFILTER_OPTIONS_PBUFF_FILTERING = "Player Buff Filtering"
DFILTER_OPTIONS_FDEBUFF_FILTERING = "Focus Debuff Filtering"
DFILTER_OPTIONS_FBUFF_FILTERING = "Focus Buff Filtering"
DFILTER_OPTIONS_COUNT = "Show Debuff/Buff Count"
DFILTER_OPTIONS_COOLDOWNCOUNT = "CooldownCount Timers"
DFILTER_OPTIONS_COMBAT = "Only Show During Combat"
DFILTER_OPTIONS_TOOLTIPS = "Show Tooltips"
DFILTER_OPTIONS_BACKDROP = "Show Backdrop"
DFILTER_OPTIONS_LOCK = "Lock Frames"
DFILTER_OPTIONS_SCALE = "Scale"

DFILTER_OPTIONS_TARGET_TOOLTIP = "The target you want to configure."
DFILTER_OPTIONS_GROW_TOOLTIP = "The direction buffs or debuffs will grow."
DFILTER_OPTIONS_ROW_TOOLTIP = "The number of buffs or debuffs to display per row."
DFILTER_OPTIONS_SELFAPPLIED_TOOLTIP = "Only show buffs and debuffs that you have applied yourself."
DFILTER_OPTIONS_DONTCOMBINE_TOOLTIP = "Don't combine multiple stacks of a buff or debuff into one icon."
DFILTER_OPTIONS_DEBUFF_FILTERING_TOOLTIP = "Enables or disables debuff filtering on your target."
DFILTER_OPTIONS_BUFF_FILTERING_TOOLTIP = "Enables or disables buff filtering on your target."
DFILTER_OPTIONS_PDEBUFF_FILTERING_TOOLTIP = "Enables or disables debuff filtering on yourself."
DFILTER_OPTIONS_PBUFF_FILTERING_TOOLTIP = "Enables or disables buff filtering on yourself."
DFILTER_OPTIONS_FDEBUFF_FILTERING_TOOLTIP = "Enables or disables debuff filtering on your focus target."
DFILTER_OPTIONS_FBUFF_FILTERING_TOOLTIP = "Enables or disables buff filtering on your focus target."
DFILTER_OPTIONS_COUNT_TOOLTIP = "Shows a counter next to each frame, displaying the total number of buffs or debuffs."
DFILTER_OPTIONS_COOLDOWNCOUNT_TOOLTIP = "Displays CooldownCount-style timers via OmniCC."
DFILTER_OPTIONS_COMBAT_TOOLTIP = "Hides each filter frame until you enter combat."
DFILTER_OPTIONS_TOOLTIPS_TOOLTIP = "Show tooltips when mousing over buffs and debuffs."
DFILTER_OPTIONS_BACKDROP_TOOLTIP = "Shows a backdrop under each filter frame to assist in moving them."
DFILTER_OPTIONS_LOCK_TOOLTIP = "Locks the frames, allowing mouse click-thru.\n\nNote: buff/debuff tooltips will not show when the frames are locked."
DFILTER_OPTIONS_SCALE_TOOLTIP = "Scales the frames up or down in size."

--end